### ISSUE TITLE
404 on CertSimple site

### ISSUE THREAD

**Issue by deltab** [certsimple/rosetta-stone#25]
I'm getting a 404 Not Found response on https://certsimple.com/js/blog/dist/rosetta-stone.js, when trying to load https://certsimple.com/rosetta-stone, so only the footer appears.

**Comment by carlwgeorge** [comment]
Same for me, https://certsimple.com/rosetta-stone is only showing the footer, no other content.

**Comment by limeblack** [comment]
bump blank page for me

**Comment by Gunstick** [comment]
bump bump :-)

**Comment by carlwgeorge** [comment]
I miss this site. 😞

**Comment by mikemaccana** [comment]
OK finally going to fix this. We hosted this as a node module in our larger app, which worked fine, but changes to the larger app keep affecting the rosetta stone.

We've recently had a bunch of interest now Solaris has been killed, and I'm going to do a bunch off work here and build this into its own self-hosted app on its own domain. Thanks for your patience.

**Comment by mikemaccana** [comment]
And it's back up!
